pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
        echo "this is my first jenkins pipeline"
      }
    }
  }
}
